---
# handlers file for newrelic-agent

- name: restart newrelic-infra on linux
  service: name=newrelic-infra state=restarted

- name: restart newrelic-infra on windows
  win_service: name=newrelic-infra state=restarted